spring:
  application:
    name: gitlab-issue-merge
  main:
    web-application-type: none

feign:
  hystrix:
    enabled: false
  client:
    config:
      gitlab:
        loggerLevel: full

logging:
  level:
    root: info
    sun.net.www.protocol.http.HttpURLConnection: info
    com.ct.gim: info

